package pr

import (
	"fmt"
	"strings"
	"time"

	"github.com/SaiPisey2/noisefloor/internal/store"
)

// Evidence is what every proposal body states in numbers a reviewer who
// does not trust noisefloor can check against their own Prometheus: the
// observation window, how many episodes were counted, and what fraction of
// them were short-lived or silenced.
type Evidence struct {
	Group, AlertName string

	Fires          int
	ShortLivedRate float64
	SilencedRate   float64
	Confidence     float64

	WindowStart, WindowEnd time.Time

	// SilencedBy is every silence that covered at least one of this rule's
	// firing episodes in the window -- collect.CoveringSilences. Who
	// silenced it, and when.
	SilencedBy []store.Silence
}

func (e Evidence) windowDays() float64 {
	return e.WindowEnd.Sub(e.WindowStart).Hours() / 24
}

// RetireBody renders a retire proposal's PR body: the evidence table the
// design doc and issue #8 specify (fires, short-lived %, silenced % with
// who and when, confidence, observation window), plus a "how to check
// this" section a reviewer can run themselves.
func RetireBody(e Evidence) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## noisefloor: retire `%s`\n\n", e.AlertName)
	fmt.Fprintf(&b,
		"Proposed for deletion: `%s` / `%s`. This rule crosses noisefloor's retire "+
			"threshold on the evidence below, gathered over the observation window "+
			"stated here -- not asserted, checkable.\n\n", e.Group, e.AlertName)

	b.WriteString("| metric | value |\n")
	b.WriteString("| --- | --- |\n")
	fmt.Fprintf(&b, "| fires | %d |\n", e.Fires)
	fmt.Fprintf(&b, "| short-lived | %s (resolved before anyone could act) |\n", formatPercent(e.ShortLivedRate))
	fmt.Fprintf(&b, "| silenced | %s |\n", formatPercent(e.SilencedRate))
	fmt.Fprintf(&b, "| confidence | %.2f |\n", e.Confidence)
	fmt.Fprintf(&b, "| observation window | %s to %s (%s) |\n",
		e.WindowStart.Format(time.RFC3339), e.WindowEnd.Format(time.RFC3339), formatWindow(e.windowDays()))
	b.WriteString("\n")

	b.WriteString(silencedBySection(e.SilencedBy))
	b.WriteString("\n")

	fmt.Fprintf(&b,
		"**How to check this**\n\nRun the same range query against your own "+
			"Prometheus, over the same window:\n\n    ALERTS{alertname=%q}\n\n"+
			"Count episodes as one continuous run of `alertstate=\"firing\"` samples "+
			"on a single series, gap-tolerant to one query step. You should find "+
			"approximately %d episodes, %s of them shorter than this rule's "+
			"short-lived threshold.\n\n",
		e.AlertName, e.Fires, formatPercent(e.ShortLivedRate))

	b.WriteString("---\nGenerated by noisefloor from stored ALERTS and Alertmanager " +
		"silence history over the window above.\n")
	return b.String()
}

// TuneBody renders a tune proposal's PR body: the counterfactual sentence
// stated explicitly (remediate.Sentence, passed in already computed --
// this package does not re-derive it), plus the same checkable window and
// episode count a retire body carries.
func TuneBody(e Evidence, currentFor, candidateFor time.Duration, sentence string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## noisefloor: tune `%s`\n\n", e.AlertName)
	fmt.Fprintf(&b, "Proposed change: `%s` / `%s`. Raise `for: %s` to `for: %s`.\n\n",
		e.Group, e.AlertName, formatDuration(currentFor), formatDuration(candidateFor))
	fmt.Fprintf(&b, "%s\n\n", sentence)

	b.WriteString("| metric | value |\n")
	b.WriteString("| --- | --- |\n")
	fmt.Fprintf(&b, "| fires | %d |\n", e.Fires)
	fmt.Fprintf(&b, "| confidence | %.2f |\n", e.Confidence)
	fmt.Fprintf(&b, "| observation window | %s to %s (%s) |\n",
		e.WindowStart.Format(time.RFC3339), e.WindowEnd.Format(time.RFC3339), formatWindow(e.windowDays()))
	b.WriteString("\n")

	fmt.Fprintf(&b,
		"**How to check this**\n\nRun the same range query against your own "+
			"Prometheus, over the same window:\n\n    ALERTS{alertname=%q}\n\n"+
			"For each episode, add the CURRENT `for: %s` back onto its firing "+
			"duration -- that is how long the underlying condition actually held, "+
			"which is what a candidate `for:` is compared against (see the "+
			"counterfactual sentence above). Count how many of the %d episodes "+
			"stay under the candidate `for: %s`; that share is the suppressed rate "+
			"stated above.\n\n",
		e.AlertName, formatDuration(currentFor), e.Fires, formatDuration(candidateFor))

	b.WriteString("---\nGenerated by noisefloor from stored ALERTS history over the window above.\n")
	return b.String()
}

func silencedBySection(sils []store.Silence) string {
	if len(sils) == 0 {
		return "**Silenced by:** nobody -- no silence covered this rule's firing time in the window.\n"
	}
	var b strings.Builder
	b.WriteString("**Silenced by:**\n\n")
	for _, s := range sils {
		comment := s.Comment
		if comment == "" {
			comment = "(no comment)"
		}
		fmt.Fprintf(&b, "- %s, %s to %s: %s\n",
			s.CreatedBy, s.StartsAt.Format(time.RFC3339), s.EndsAt.Format(time.RFC3339), comment)
	}
	return b.String()
}

func formatPercent(rate float64) string {
	return fmt.Sprintf("%.0f%%", rate*100)
}

// formatWindow renders an observation window's length in whole days when it
// divides evenly, and fractional otherwise -- "30d" reads better than
// "30.0d", but a truncated window (e.g. a fresh Prometheus) still needs the
// fraction to be honest about its length.
func formatWindow(days float64) string {
	if days == float64(int(days)) {
		return fmt.Sprintf("%.0fd", days)
	}
	return fmt.Sprintf("%.1fd", days)
}

// formatDuration renders a duration compactly, the same shape
// internal/remediate and internal/report use: every unit
// time.Duration.String would print gets noisy at episode-duration
// precision (3m0s, 1h2m0s), and this goes straight into prose and a `for:`
// value a reviewer reads once.
func formatDuration(d time.Duration) string {
	if d <= 0 {
		return "0s"
	}
	d = d.Round(time.Second)

	h := d / time.Hour
	d -= h * time.Hour
	m := d / time.Minute
	d -= m * time.Minute
	s := d / time.Second

	units := [3]struct {
		v int64
		u string
	}{{int64(h), "h"}, {int64(m), "m"}, {int64(s), "s"}}

	first := -1
	for i, u := range units {
		if u.v != 0 {
			first = i
			break
		}
	}
	if first == -1 {
		return "0s"
	}
	last := len(units) - 1
	for last > first && units[last].v == 0 {
		last--
	}

	out := ""
	for i := first; i <= last; i++ {
		out += fmt.Sprintf("%d%s", units[i].v, units[i].u)
	}
	return out
}
